downloads: d3.v7.min.js force-graph html2canvas.min.js jspdf.umd.min.js

d3.v7.min.js:
	wget https://d3js.org/d3.v7.min.js

force-graph:
	wget https://unpkg.com/force-graph

html2canvas.min.js:
	wget https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js

jspdf.umd.min.js:
	wget https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js

clean:
	rm d3.v7.min.js force-graph html2canvas.min.js jspdf.umd.min.js
